/*
 * com_driver_cfg.h
 *
 *  Created on: May 19, 2025
 *      Author: alperenyazici
 */

#ifndef COM_DRIVER_CFG_COM_DRIVER_CFG_H_
#define COM_DRIVER_CFG_COM_DRIVER_CFG_H_

#define COM_BUCK_VOLTAGE_INFO_MESSAGE_ID	0U
#define COM_BUCK_CURRENT_INFO_MESSAGE_ID	1U
#define COM_SYSTEM_INFO_MESSAGE_ID			2U
#define COM_TOTAL_MESSAGE_ID			 	3U



#define COM_BUCK_OUTPUT_VOLTAGE_SIGNAL_ID	0U
#define COM_BUCK_INPUT_VOLTAGE_SIGNAL_ID	1U
#define COM_BUCK_OUTPUT_CURRENT_SIGNAL_ID	2U
#define COM_BUCK_INPUT_CURRENT_SIGNAL_ID	3U
#define COM_SYSTEM_TEMPERATURE_SIGNAL_ID	4U
#define COM_SYSTEM_STATE_SIGNAL_ID			5U
#define COM_SYSTEM_ERROR_STATE_SIGNAL_ID	6U
#define COM_TOTAL_SIGNAL_ID					7U
#endif /* COM_DRIVER_CFG_COM_DRIVER_CFG_H_ */
